name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-cd:
    uses: sparetimedevs/github-actions-base/.github/workflows/ci-pipeline-gradle-template.yml@main
    with:
      java-version: 21
